name: Publish to StreamX

on:
  repository_dispatch:
    types:
      - resource-published

permissions:
  id-token: write
  contents: read

jobs:
  check-event-status:
    runs-on: ubuntu-latest
    steps:
      - env:
          CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload) }}
        run: |
          echo $CLIENT_PAYLOAD
          echo "Status: ${{ github.event.client_payload.status }}"
          echo "Path: ${{ github.event.client_payload.path }}"

  publish-to-streamx:
    if: (github.event.client_payload.status == 200 || github.event.client_payload.status == 204) && endsWith(github.event.client_payload.path, '.md')
    runs-on: ubuntu-latest
    steps:
      - name: Prepare ingestion variables
        id: vars
        shell: bash
        run: |
          sleep 1s
          streamx_key=$(echo "${{ github.event.client_payload.path }}" | sed 's/\.md$//g')
          eds_page_url="${{ vars.EDS_DOMAIN_URL }}$streamx_key"
          echo "Page URL: $eds_page_url"
          echo "StreamX key: $streamx_key"
          echo "streamx_key=$streamx_key" >> "$GITHUB_OUTPUT"
          echo "eds_page_url=$eds_page_url" >> "$GITHUB_OUTPUT"
